version: '1.8'
services:
  es01:
    image: elasticsearch:7.3.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true 
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
    ports:
      - 19200:9200
      - 19300:9300
    networks:
      - esnet
  kibana:
    image: kibana:7.3.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - I18N_LOCALE=zh-CN
      - xpack.monitoring.ui.container.elasticsearch.enabled=false
    ports:
      - 15601:5601    
    networks:
      - esnet
  dejavu:
    image: appbaseio/dejavu:3.4.7
    container_name: dejavu
    ports:
        - '11358:1358'
    links:
        - es01
    networks:
      - esnet

networks:
  esnet:
    driver: bridge